
stages:
  - build
  - test
  - check

include:
# Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

# Build (stable & edge)
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build:stable
      anod-args: run build_stable --latest
      save-component: true

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build:edge
      anod-args: run build_edge --latest
      linux: true
      windows: true
      save-component: true

# Testing (stable & edge)
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: test:stable
      needs: ["build:stable:linux"]
      cpus: 2
      # --latest should not be used here because it causes Anod to re-download
      # components from Cathod instead of using the ones built in this pipeline
      # by the build job.
      anod-args: run test_stable

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: test:edge
      needs: ["build:edge:linux"]
      windows-needs: ["build:edge:windows"]
      cpus: 2
      linux: true
      windows: true
      # --latest should not be used here because it causes Anod to re-download
      # components from Cathod instead of using the ones built in this pipeline
      # by the build job.
      anod-args: run test_edge
